version: '3.4'

services:
  tfgsoftalba:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_tfgalba
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

  



 
